# Soring, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [3]:
author = "Ganesh patil. https://github.com/ganeshpatil9766/Python/"

## Sorting

### Q1. Sort x along the second axis.

In [6]:
x = np.array([[1,4],[3,1]])
np.sort(x)

array([[1, 4],
       [1, 3]])

In [7]:
print(x.sort(axis=1))

None


### Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [11]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
np.lexsort((first_names, surnames))

array([1, 2, 0], dtype=int64)

### Q3. Get the indices that would sort x along the second axis.

In [12]:
x = np.array([[1,4],[3,1]])
np.argsort(x, axis=1)

array([[0, 1],
       [1, 0]], dtype=int64)

In [13]:
np.argsort(x, axis=0)

array([[0, 1],
       [1, 0]], dtype=int64)

### Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [15]:
x = np.random.permutation(10)
print ("x =", x)


x = [3 9 1 5 4 6 8 7 2 0]


In [17]:
print( "\nCheck the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5\n", )
out = (np.partition(x, 5))
x.partition(5) # in-place equivalent
assert np.array_equal(x, out)
print (out)


Check the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5

[2 0 1 3 4 5 6 7 8 9]


### Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [18]:
x = np.random.permutation(10)
print ("x =", x)
partitioned = np.partition(x, 3)
indices = np.argpartition(x, 3)
print( "partitioned =", partitioned)
print( "indices =", partitioned)
assert np.array_equiv(x[indices], partitioned)

x = [1 5 6 2 4 3 7 9 8 0]
partitioned = [0 1 2 3 4 5 7 9 8 6]
indices = [0 1 2 3 4 5 7 9 8 6]


## Searching

### Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [19]:
x = np.random.permutation(10).reshape(2, 5)
print( "x =", x)
print( "maximum values =", np.max(x, 1))
print( "max indices =", np.argmax(x, 1))
print( "minimum values =", np.min(x, 1))
print( "min indices =", np.argmin(x, 1))


x = [[4 6 0 3 5]
 [7 8 1 2 9]]
maximum values = [6 9]
max indices = [1 4]
minimum values = [0 1]
min indices = [2 2]


In [20]:
x = np.random.permutation(10).reshape(2, 5)
print( "x =", x)
print( "maximum values =", np.max(x, 1))
print( "max indices =", np.argmax(x, 1))
print( "minimum values =", np.min(x, 1))
print( "min indices =", np.argmin(x, 1))


x = [[8 9 4 3 1]
 [7 0 2 6 5]]
maximum values = [9 7]
max indices = [1 0]
minimum values = [1 0]
min indices = [4 1]


### Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [21]:
x = np.array([[np.nan, 4], [3, 2]])
print( "maximum values ignoring NaNs =", np.nanmax(x, 1))
print( "max indices =", np.nanargmax(x, 1))
print( "minimum values ignoring NaNs =", np.nanmin(x, 1))
print( "min indices =", np.nanargmin(x, 1))

maximum values ignoring NaNs = [4. 3.]
max indices = [1 0]
minimum values ignoring NaNs = [4. 2.]
min indices = [1 1]


In [22]:
x = np.array([[np.nan, 4], [3, 2]])
print( "maximum values ignoring NaNs =", np.nanmax(x, 0))
print( "max indices =", np.nanargmax(x, 0))
print( "minimum values ignoring NaNs =", np.nanmin(x, 0))
print( "min indices =", np.nanargmin(x, 0))

maximum values ignoring NaNs = [3. 4.]
max indices = [1 0]
minimum values ignoring NaNs = [3. 2.]
min indices = [1 1]


### Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [23]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print( "Values bigger than 2 =", x[x>2])
print( "Their indices are ", np.nonzero(x > 2))
assert np.array_equiv(x[x>2], x[np.nonzero(x > 2)])
assert np.array_equiv(x[x>2], np.extract(x > 2, x))

Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


In [24]:
np.extract(x > 2, x)

array([3, 3, 5])

### Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [25]:
x = np.array([[1, 2, 3], [1, 3, 5]])
np.flatnonzero(x >2)

array([2, 4, 5], dtype=int64)

In [27]:
x.ravel().nonzero()

(array([0, 1, 2, 3, 4, 5], dtype=int64),)

### Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [29]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x <0, 0, x)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

### Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [30]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x,y)

array([0, 2, 1, 3], dtype=int64)

## Counting

### Q12. Get the number of nonzero elements in x.

In [31]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5

In [33]:
len(x[x != 0])

5