# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

## Matrix and vector products

### Q1. Predict the results of the following code.

In [4]:
x = [1,2]
y = [[4, 1], [2, 2]]

print(x)
print(y)

print( np.dot(x, y))
print (np.dot(y, x))
print( np.matmul(x, y))
print (np.inner(x, y))
print( np.inner(y, x))

[1, 2]
[[4, 1], [2, 2]]
[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


### Q2. Predict the results of the following code.

In [5]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print (np.dot(y, x))
print( np.matmul(y, x))


[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


### Q3. Predict the results of the following code.

In [6]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print( np.vdot(x, y))
print(np.vdot(y, x))
print( np.dot(x.flatten(), y.flatten()))
print(np.inner(x.flatten(), y.flatten()))
print((x*y).sum())

30
30
30
30
30


### Q4. Predict the results of the following code.

In [7]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print( np.inner(x, y))
print (np.inner(y, x))
print( np.outer(x, y))
print (np.outer(y, x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

### Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [8]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
np.linalg.cholesky(x)

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

In [11]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
L = np.linalg.cholesky(x)
print (L)
assert np.array_equal(np.dot(L, L.T.conjugate()), x)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [13]:
np.dot(L, L.T.c())


array([[  4.,  12., -16.],
       [ 12.,  37., -43.],
       [-16., -43.,  98.]])

### Q6. Compute the qr factorization of x and verify it.

In [22]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q, r = np.linalg.qr(x)
print ("q=\n", q, "\nr=\n", r)


q=
 [[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r=
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [23]:
assert np.allclose(np.dot(q, r), x)

In [24]:
np.dot(q, r)

array([[ 12.      , -51.      ,   4.000001],
       [  6.      , 167.      , -68.      ],
       [ -4.      ,  24.      , -41.      ]], dtype=float32)

### Q7. Factor x by Singular Value Decomposition and verify it.

In [26]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U, s, V = np.linalg.svd(x, full_matrices=False)
print( "U=\n", U, "\ns=\n", s, "\nV=\n", V)


U=
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
 [3.       2.236068 2.       0.      ] 
V=
 [[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


In [27]:
assert np.allclose(np.dot(U, np.dot(np.diag(s), V)), x)


In [28]:
np.dot(U, np.dot(np.diag(s), V))

array([[1., 0., 0., 0., 2.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.]], dtype=float32)

## Matrix eigenvalues

### Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [32]:
x = np.diag((1, 2, 3))
eigenvals = np.linalg.eig(x)[0]
eigenvals_ = np.linalg.eigvals(x)
assert np.array_equal(eigenvals, eigenvals_)
print( "eigenvalues are\n", eigenvals)
eigenvecs = np.linalg.eig(x)[1]
print( "eigenvectors are\n", eigenvecs)

eigenvalues are
 [1. 2. 3.]
eigenvectors are
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
np.linalg.eig(x)

(array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

### Q9. Predict the results of the following code.

In [35]:
np.dot(x, eigenvecs)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [36]:
eigenvals * eigenvecs

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [81]:
print( np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs))

## Norms and other numbers

### Q10. Calculate the Frobenius norm and the condition number of x.

In [39]:
x = np.arange(1, 10).reshape((3, 3))
print(np.linalg.norm(x, 'fro'))
print(np.linalg.cond(x, 'fro'))

16.881943016134134
3.193239515623568e+17


### Q11. Calculate the determinant of x.

In [40]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.det(x)

-2.0000000000000004

In [41]:
 x[0, 0] * x[1, 1] - x[0, 1] * x[1, 0]

-2

### Q12. Calculate the rank of x.

In [42]:
x = np.eye(4)
out1 = np.linalg.matrix_rank(x)
out1

4

In [43]:
np.linalg.svd(x)

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([1., 1., 1., 1.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [45]:
np.linalg.svd(x)[1].size

4

### Q13. Compute the sign and natural logarithm of the determinant of x.

In [46]:
x = np.arange(1, 5).reshape((2, 2))
sign, logdet = np.linalg.slogdet(x)
det = np.linalg.det(x)

print(sign)
print(logdet)
print(det)

-1.0
0.6931471805599455
-2.0000000000000004


In [47]:
sign == np.sign(det)

True

In [52]:
logdet == np.log(np.abs(det))

True

### Q14. Return the sum along the diagonal of x.

In [54]:
x = np.eye(4)
np.diag(x).sum()

4.0

In [55]:
np.trace(x)

4.0

## Solving equations and inverting matrices

### Q15. Compute the inverse of x.

In [57]:
x = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(x)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])